##################################################################################################
# Details service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: details-svc
  labels:
    app: details-svc
    service: details-svc
spec:
  ports:
  - name: http
    protocol: TCP
    port: 9082
    targetPort: 9082
  selector:
    app: details-svc
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ctibco-details-svc
  labels:
    account: details-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-svc-v1
 # annotations:
 #   "sidecar.jaegertracing.io/inject": "true"
  labels:
    app: details-svc
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details-svc
      version: v1
  template:
    metadata:
      labels:
        app: details-svc
        version: v1
    spec:
      serviceAccountName: ctibco-details-svc
      containers:
      - env:
        - name: DETAILS_MY_PORT
          value: "9082"
        - name: BW_PROFILE
          value: "docker"
        - name: BW_LOGLEVEL
          value: "ERROR" 
        - name: BW_JAVA_OPTS
          value: "-Dbw.engine.opentracing.enable=true" 
        - name: BW_PROMETHEUS_ENABLE
          value: "true"
        image: 172.31.28.242:8083/details:2.0.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: 500Mi
            cpu: 500m
          limits:
            memory: 900Mi
            cpu: 1000m
        name: details-svc
        ports:
        - containerPort: 9082
      imagePullSecrets:
        - name: regcred
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - http:
      paths:
      - path: /details
        backend:
          serviceName: details-svc
          servicePort: 9082
